### ISSUE TITLE
I have this Error. Pls help!!

### ISSUE THREAD

**Issue by tomkull1999** [lpossamai/send_smsglobal_zabbix#1]
date +%H:%M:%: Sending SMS Text to 84364803501
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M100   100  100    26  100    74     28     79 --:--:-- --:--:-- --:--:--    79
ERROR: 88 SMSGlobalMsgID:
date +%H:%M:%: SMS Text sent to 84364803501
MESSAGE: Disaster web:HTTP service is down on web-status-PROBLEM

**Comment by lpossamai** [comment]
Please, execute the script in debug mode:

`bash -x send_sms.sh`
