### ISSUE TITLE
Can you please provide me how to use the media type in action

### ISSUE THREAD

**Issue by Ahmadhashem86** [lpossamai/send_smsglobal_zabbix#2]

**Comment by lpossamai** [comment]
Not sure what you mean.. but you can follow the README:

```
How to add the script to Zabbix (Tested on Zabbix Server 3.4):

    Administration > Media Types
    Add a new "Script" media Type

		Name: SMS Global - SMS
		Type: Script
		Script name: send_sms.sh
		Script parameters:
		PARAMETER 1: {ALERT.SENDTO}
		PARAMETER 2: {ALERT.MESSAGE}
```

Or check out [Zabbix Documentation](https://www.zabbix.com/documentation/current/manual/config/notifications/media) for more information on Media Types.

**Comment by Ahmadhashem86** [comment]
I mean I have this in Administration > Media Types
but how zabbix will know the  phone number to send to?

I have added an action when one server is down will send a sms as shown in bilds

![bild1](https://user-images.githubusercontent.com/67095164/101155286-2fe39300-3627-11eb-944d-d962276f8d7e.png)
![bild2](https://user-images.githubusercontent.com/67095164/101155289-2fe39300-3627-11eb-8347-a6693aae09d4.png)
![bild3](https://user-images.githubusercontent.com/67095164/101155291-307c2980-3627-11eb-8af3-2099f970ca18.png)


Is this a good configuration or should I set the phone number in the script?

**Comment by lpossamai** [comment]
That's on your username configuration. The mobile phone is set per user. Please check documentation. This is not an issue with the script.
